config/routes.rb
BestBay::Application.routes.draw do

  root to: "products#homepage"

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :notifications

  match '/search', to: 'products#search'
  match '/signup', to: 'users#new'
  match '/profile', to: 'users#profile'
  match '/selling', to: 'users#selling'
  match '/buying', to: 'users#buying'
  match '/notification', to: 'users#notification'
  
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/home', to: 'products#homepage'
  resources :products, only:[:new, :create, :index, :show]

  match 'products/:id/buyout', to: 'products#buyout'
  match 'products/:id/bid', to: 'products#bid'
  match 'products/:id/rate', to: 'products#rate'
  match 'post' => 'products#new'
  match 'products/:id/cancel', to: 'products#cancel'












end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="/">Best Bay</a>
    by ThunderGrip
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", '#' %></li>
      <li><%= link_to "Contact Us", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container" style="width:90%;">
      <%= link_to "BestBay", root_url , :id=>'logo' %>
      <nav>
      <ul class="nav pull-right">
        <li><%= link_to "Home",    root_url %></li>
		<li id="notification_header">
		<% if new_notification != 0 %>
		<% note_name =  new_notification .to_s() + " new messages!"%>
		  <%= link_to note_name, '/notification' %>
		<% end %>
		</li>
        <% if signed_in? %>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Post New Item", '/post' %></li>
                <li><%= link_to "My BestBay", '/selling' %></li>
				<li><%= link_to "Profile Setting", '/profile' %></li>
				<li><%= link_to "Notification", '/notification' %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
        <% else %>
            <li><%= link_to "Sign in", '/signin' %></li>
			<li><%= link_to "Sign up", '/signup' %></li>
        <% end %>

      </ul>
    </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BestBay</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%=  render 'layouts/shim' %>
</head>
<body>

<%= render 'layouts/header' %>
<div class="container">
  <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
  <%end%>
  <%= yield %>

</div>
<%= render 'layouts/footer' %>


</body>
</html>